version: '3'
services:

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  shyv:
    image: "shyv"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - mongodb

